---
- hosts: ukmonhelper
  vars:
    srcdir: /mnt/e/dev/planetgraphs/OrbitCalcs/orbitcalcs   
    destdir: ~/mmwebsite/planetgraphs
  tasks:
  - name: Ensures logs exists
    file: path={{destdir}}/../logs state=directory
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/config', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/template.sch', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/charter.sh', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/getmpcdata.sh', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/pgpreprocess.sh', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/makecometpages.sh', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/create_page.php', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/cometmain.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/Comets.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/Comets.h', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/ConjunctionCalculator.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/DateMaths.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/InitStaticData.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/MagAndSize.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/main.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/MoonCalcs.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/OrbitCalcs.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/OrbitCalcs.h', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/Outputter.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/Outputter.h', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/Perturbations.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/Pluto.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/summarycalc.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/TransitRiseSet.cpp', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/Makefile', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/crontabs.txt', dest: '{{destdir}}', mode: '644', backup: no }
